### ISSUE TITLE
only show one page

### ISSUE THREAD

**Issue by andyyxw** [derhuerst/print-any-html#3]
The print layer only show one page，actually I have more content.
I want to know what's wrong, please!

![Snipaste_2020-04-13_18-38-58](https://user-images.githubusercontent.com/41931722/79114518-10f17180-7db6-11ea-918e-de04c95b25d7.png)

**Comment by derhuerst** [comment]
Please provide your whole code, so that I can reproduce the issue.

**Comment by derhuerst** [comment]
I‘m going to close this. Please reopen if you have more details on how to reproduce this issue.
